kind: Service
apiVersion: v1
metadata:
  name: awsomeui-service
  labels:
    app: awsomeui
spec:
  type: ClusterIP
  selector:
    app: awsomeui-deployment
  ports:
    - port: 8090
      targetPort: 8090
